### PR TITLE
Fix violation code conflicts with `flake8-import-order`

### PR DESCRIPTION
**Pull request by labrys**
This adds 50 to the violation codes:

| OLD CODE | NEW CODE | VIOLATION |
| ------------ | ------------- | ------------ |
| I200 | I250 | Unnecessary import alias
| I200 | I251 | Banned import

### CODE REVIEW

**Comment by labrys** [comment]
Closes #106

**Comment by labrys** [comment]
I'll have to look at why the tests are failing later

**Comment by adamchainz** [comment]
Hi,

Sorry I didn't reply before.

Would you have time to rebase this on top of changes since, and ensure the tests pass?

Thanks,

Adam

**Comment by adamchainz** [comment]
Superceded by #176.

**Comment by adamchainz** [comment]
#176 was merged and this has been released in version 4.0.0: https://pypi.org/project/flake8-tidy-imports/4.0.0/ 🎺

**Pull request closed without merging**
